---
- name: 웹 서버 설정과 인증 페이지 구성
  hosts: all
  vars_files:
    - vars/vars.yml
  tasks:
    # 1) 패키지 설치 - firewalld, httpd, mod_ssl
    - name: 패키지 설치
      ansible.builtin.yum:
        name: "{{ pkgs }}"
        state: present

    # 2) /etc/httpd/conf/httpd.conf
    # 3) /var/www/html/.htaccess
    # 4) /etc/httpd/secrets/ 생성
    # 5) /etc/httpd/secrets/htpasswd 생성  
    # 6) /var/www/html/index.html
    - name: httpd.conf 파일
      ansible.builtin.copy:
        src: "{{ conf_web_src }}"
        dest: "{{ conf_web_dst }}"
        owner: root
        group: root
        mode: '0644'

    - name: htaccess 파일
      ansible.builtin.copy:
        src: "{{ htaccess_src }}"
        dest: "{{ htaccess_dst }}"
        owner: apache
        group: apache
        mode: '0400'

    - name: /etc/httpd/secrets 디렉토리 생성
      ansible.builtin.file:
        path: /etc/httpd/secrets
        state: directory
        owner: apache
        group: apache
        mode: '100'

    - name: /etc/httpd/secrets/htpasswd 파일
      ansible.builtin.copy:
        src: "{{ htpasswd_src }}"
        dest: "{{ htpasswd_dst }}"
        owner: apache
        group: apache
        mode: '0400'

    - name: /var/www/html/index.html 파일
      ansible.builtin.copy:
        content: "{{ ansible_fqdn }} : {{ ansible_all_ipv4_addresses }}"
        dest: "{{ mainpage }}"

    # 7) httpd, firewalld 서비스 기동
    - name: 서비스 기동
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      loop: "{{ svcs }}"
    
    # 8) 방화벽 등록 - http, https
    - name: 방화벽 포트 등록
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ fw_svcs }}"

    # 9) 웹요청
- name: 웹요청(인증)
  hosts: localhost
  vars_files:
    - vars/secret.yml
  tasks:
    - name: 웹요청 인증
      ansible.builtin.uri:
        url: http://ansible1.example.com
        user: "{{ user }}"
        password: "{{ pw }}"
        validate_certs: false
        force_basic_auth: true
        return_content: true
        status_code: 200
      register: output

    - name: 웹 페이지 출력
      ansible.builtin.debug:
        msg: "{{ output }}"
