---
- name: 파일 서버 설정
  hosts: fileservers
  gather_facts: true
  tasks:
    - name: 변수 포함
      ansible.builtin.include_vars: path.yml
    - name: 원격 디렉토리 생성
      ansible.builtin.file:
        path: "{{ path.fileserver }}"
        state: directory
        mode: '0755'
      register: result

    - name: Result 변수 내용 확인
      ansible.builtin.debug:
        var: result
...
