---
- name: 복구
  hosts: all
  gather_facts: true
  tasks:
    # 1) 방화벽 포트 제거 - http, https
    - name: 방화벽 제거
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled
      loop:
        - http
        - https

    # 2) 서비스 내리기 - httpd, mariadb
    - name: 서비스 내리기
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - httpd
        - mariadb

    # 3) 설정 삭제 - /var/www/html/index.html
    - name: 설정 삭제
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    # 4) 패키지 삭제 - httpd, mariadb-server
    - name: 패키지 삭제
      ansible.builtin.yum:
        name:
          - http
          - mariadb-server
        state: absent
...
