---
- name: Task Failure Exercise
  hosts: databases
  vars:
    web_package: httpd     # 잘못된 정보 그대로 입력
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Check local time
      command: date
      register: command_result

    - name: Print local time
      ansible.builtin.debug:
        var: command_result.studnet

    - name: Attepmt to set up a web server
      block:
        - name: Install {{ web_package }} package
          ansible.builtin.yum:
            name: "{{ web_package }}"
            state: present
      rescue:
        - name: Install {{ db_package }} package
          ansible.builtin.yum:
            name: "{{ db_package }}"
            state: present
      always:
        - name: Start {{ db_service }} service
          ansible.builtin.service:
            name: "{{ db_service }}"
            state: started