---
- name: 웹 서버 구성
  hosts: all
  vars_files:
    - vars/variable.yml
    
  tasks:
    - name: 방화벽에 등록 해제
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled
      loop:
        "{{ fw_webs }}"

   

    - name: 서비스 해제
      file:
        path: /var/www/html/index.html
        state: absent
        

     

    - name: 패키지 설치
      ansible.builtin.dnf:
        name:
          - "{{ pkg_web }}"
          - "{{ pkg_web_https }}"
          - "{{ pkg_python }}"
        state: absent

   

   

