---
- name: MariaDB server is installed
  hosts: databases
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
    db_service: mariadb
    resources_url: http://ansible.example.com
    config_file_url: "{{ resources_url }}/my.cnf.standard"
    config_file_dst: /etc/my.cnf
  vars_prompt:
    - name: mariadb_root_password
      prompt: What would you set the password for?
  tasks:
    - name: "{{ db_packages }} packages are installed"
      yum:
        name: "{{ db_packages }}"
        state: present
      notify:
        - set db password

    - name: Make sure the database service is running
      service:
        name: "{{ db_service }}"
        state: started
        enabled: true

    - name: The {{ config_file_dst }} file has been installed
      get_url:
        url: "{{ config_file_url }}"
        dest: "{{ config_file_dst }}"
        owner: mysql
        group: mysql
        force: yes
      notify:
        - restart db service

    - name: Write root login credentials
      copy:
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: 0600
        content: |
          [client]
          user=root
          password={{ mariadb_root_password }}
          socket=/var/lib/mysql/mysql.sock

  handlers:
    - name: restart db service
      service:
        name: "{{ db_service }}"
        state: restarted

    - name: set db password
      community.mysql.mysql_user:
        name: root
        password: soldesk1.
        priv: '*.*:ALL'
        state: present
...
