---
- name: 타임존 설정
  hosts: datacenters

  roles:
    - rhel-system-roles.timesync

  post_tasks:
    - name: 타임존 설정
      community.general.timezone:
        name: "{{ host_timezone }}"
      notify: 크로니 재시작

  handlers:
    - name: 크로니 재시작
      ansible.builtin.service:
        name: chronyd
        state: restarted
